@echo off
echo Installing PyQt5...
pip install PyQt5==5.15.9
echo Installing PyQt5-sip...
pip install PyQt5-sip
echo Installing PyQt5-Qt5...
pip install PyQt5-Qt5
echo Installing PyQtWebEngine...
pip install PyQtWebEngine==5.15.6
echo Installing other dependencies...
pip install python-dotenv bcrypt Pillow reportlab jinja2 supabase storage3 arabic-reshaper python-bidi
echo All packages installed!
pause
